### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by francopestilli**

### CODE REVIEW

**Review by klee773 — COMMENTED** [review]
Approved this one.

**Review by klee773 — APPROVED** [review]

**Comment by Oskar-Burger** [comment]
These are great changes.

**Review by faizhashmi04 — APPROVED** [review]
I approve this change

**Review by Oskar-Burger — APPROVED** [review]
yes, this just wwhat we needed.

**Review by francopestilli — COMMENTED** [review]
I think @francopestilli should add the Surnames of each Contributor

**Pull request merged**
